Repository clue/reactphp-socks, pull requests merged in 2024-05, with the labels that each got.

#113 Run tests on PHP 8.3 and update test suite
  .github/workflows/ci.yml
  composer.json
  phpunit.xml.dist
  phpunit.xml.legacy
Labels: new feature

#112 Fix typos in documentation
  CHANGELOG.md
  src/Client.php
Labels: documentation

#116 Update tests to remove defunct badssl.com
  tests/FunctionalTest.php
Labels: maintenance

#117 Update close handler to avoid unhandled promise rejections
  src/Client.php
  tests/ClientTest.php
  tests/FunctionalTest.php
  tests/TestCase.php
Labels: new feature

#118 Avoid creation of dynamic property (PHP 8.2+)
  phpunit.xml.dist
  phpunit.xml.legacy
  src/Server.php
Labels: new feature
